apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx   # Must match 'kubectl get ingressclass' output
  rules:
  - http:
      paths:
      - path: /news
        pathType: Prefix
        backend:
          service:
            name: news
            port:
              number: 80
      - path: /mail
        pathType: Prefix
        backend:
          service:
            name: mail
            port:
              number: 8080